"""add status

Revision ID: f82361275831
Revises: 3dbadee98111
Create Date: 2024-05-13 22:36:34.635876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82361275831'
down_revision: Union[str, None] = '3dbadee98111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('good', sa.Column('status', sa.Boolean(), nullable=True, comment='Продан товар'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('good', 'status')
    # ### end Alembic commands ###
